name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Authenticate with GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3️⃣ Install gcloud CLI
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

      # 4️⃣ Configure Docker to use Artifact Registry
      - name: Configure Docker for GAR
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      # 5️⃣ Build and push Docker image
      - name: Build and Push Docker image
        run: |
          IMAGE="asia-south1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/fankaar/artisan-agent-api:latest"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE .
          docker push $IMAGE

      # 6️⃣ Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy artisan-agent-api \
            --image $IMAGE \
            --region asia-south1 \
            --platform managed \
            --allow-unauthenticated \
            --timeout 900 \
            --set-env-vars "GOOGLE_GENAI_USE_VERTEXAI=${{ secrets.GOOGLE_GENAI_USE_VERTEXAI }},GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }},GOOGLE_CLOUD_LOCATION=${{ secrets.GOOGLE_CLOUD_LOCATION }},GOOGLE_CLOUD_LOCATION_LYRIA=${{ secrets.GOOGLE_CLOUD_LOCATION_LYRIA }},GOOGLE_CLOUD_STORAGE_BUCKET=${{ secrets.GOOGLE_CLOUD_STORAGE_BUCKET }}}"
